trigger: none
pool:
  name: ModuleAgent
stages:
- stage: terraformrunning
  jobs:
  - job: 
    displayName: Terraforminstall
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: terrafomrinit
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'ModuleSC'
        backendAzureRmStorageAccountName: 'ankitsgmodule'
        backendAzureRmContainerName: 'statefile'
        backendAzureRmKey: 'module.tfstate'
